### PR TITLE
do not control hue or saturation when percent is controlled, to preve…

### PR DESCRIPTION
**Pull request by oliverschulze**
…nt color or saturation change, when brightness is controlled

prevent crashing, when hue is controlled

### CODE REVIEW

**Comment by AlCalzone** [comment]
Does this mean I cannot say something like "Alexa, set XYZ saturation to 50%"?
The tradfri adapter exposes saturation as a numeric state from 0-100%. Being able to control that would be nice.

Or am I misunderstanding something?

**Comment by oliverschulze** [comment]
I have to check this, I did not control saturation yet, I just controlled the dim level of the ligts, what lead to also change the color and the saturation, that was bad.

**Comment by oliverschulze** [comment]
Hi,
I have checked, problem is, that in the german version of Alexa, there seems not to be a command like "Alexa, set XYZ saturation to 50%" ("Alexa, stelle die Sättigung von XY auf 50%). All requests for the dim level go to all connected states (sat, hue, level), so controlling the dim level, all those values are changed. 

@AlCalzone: can you control the state of dim level, saturation and color independently?

A possibility would be, to enhance the configuration by a parameter, to control the behaviour, so that both behaviours are possible.

**Comment by AlCalzone** [comment]
I think we should rethink the strategy how States are chosen to be updated. I‘ll propose ohne later when I‘m not on mobile.

**Comment by oliverschulze** [comment]
ok, looking forward to your ideas

**Comment by AlCalzone** [comment]
So here we go:
In the situation where multiple states are grouped under one smart name, saying "Alexa, set XYZ to 50%" probably means that we want to set the brightness to 50%, maybe on/off states to on (true) but nothing else.
However, when there's only one percentage based state for a smart name, we probably meant to change that one to a certain percentage, even if it is a "saturation" state.

Currently, SetPercentageRequest just sets all states that belong to a smartname. I think we should filter those before calling controlPercent.
My proposed strategy for handling a `SetPercentageRequest` would be:
1. If there's one or more states in the ID list with role `*.dimmer` and type `number`, only set those
2. Otherwise, if there's one or more states in the ID list with role `switch` and type `boolean`, only set those
3. Otherwise set all states in the ID list with type `number`.

Maybe 1. and 2. should not be mutually exclusive, idk. Anyways this strategy should allow us to control all states as expected but also not set too many states when controlling complex smart names.

**Comment by GermanBluefox** [comment]
Should I merge it?

**Comment by oliverschulze** [comment]
Hi,

I'll try to put in the changes, AlCalzone has suggested, to satisfy all needs... Give me some minutes ...

**Comment by oliverschulze** [comment]
Ok, I have integrated the proposal of ALCazone, so it should satisfy all needs now. At my home it is still working, like I wanted it. In my opinion you can merge now.

**Comment by GermanBluefox** [comment]
And now someone must verify it. Cloud uses 4600 Leuten... Ich will nicht wissen was passiert..

**Comment by oliverschulze** [comment]
Maybe Alcazone can verify it? I'm controlling around 15 Hue bulbs/Lightstrips, one Aurora Nanoleaf and a hyperion connected Ambilight Strip with it and it works.

**Comment by AlCalzone** [comment]
I'll probably get around to testing it tonight. Will report back.

**Comment by GermanBluefox** [comment]
Any news here?

**Comment by oliverschulze** [comment]
AlCalzone, did you have time to test it?

**Comment by AlCalzone** [comment]
Sorry, I forgot. Will do tonight!

**Comment by AlCalzone** [comment]
Sorry again, had problems with my dishwasher. Hope I get around to test it today.

**Comment by oliverschulze** [comment]
AlCalzone, I hope your dishwasher is doing well ;-) Had a chance to test?

**Comment by AlCalzone** [comment]
Tomorrow, I promise

**Comment by AlCalzone** [comment]
So, I tested the update with a tradfri white spectrum lightbulb. I manually created a new test device with all 3 states:
* brightness `light.dimmer` [0-100%]
* on/off `switch` [bool]
* colorTemperature `level.color.temperature` [0-100%]

Any percentage change prioritized the `brightness` over `on/off` and `colorTemperature`. 
I then removed `brightness` from the combined device:
* on/off
* colorTemperature
Now changing the percentage only changed the color temperature.

-- 

However when I now turn the light on or off, the color temperature also gets changed. "off" sets `on/off` to `false` and `colorTemperature` to 0%. "on" sets `on/off` to `true` and `colorTemperature` to 100%

**Comment by oliverschulze** [comment]
As I know the following part:

> However when I now turn the light on or off, the color temperature also gets changed. "off" sets on/off to false and colorTemperature to 0%. "on" sets on/off to true and colorTemperature to 100%

has nothing to do, with my changes, that has been there before, I think, Is the behaviour different for on/off when testing without my changes?

**Comment by AlCalzone** [comment]
I guess that has nothing to do with your changes, but would be nice if we could kill two flies with one stone ;)

**Comment by AlCalzone** [comment]
> I think, that is something out of the scope of the cloud-Module and has something to do with the lights

Is it though? If I can group multiple states in the cloud adapter config, the cloud adapter should be smart enough to only trigger those states that belong to a request from Alexa.
I think we should apply the same logic you implemented into `SetPercentageRequest` for dimmers to `TurnOnRequest` and `TurnOffRequest` when it comes to switch states, e.g.:
- Are there states with `role="switch"` in the smartname?
- If so, switch only those states
- If not, continue with the logic for dimmers.

Ultimately this is something @GermanBluefox has to decide, but I think it would make sense. After all, the adapters don't know if the updates from the cloud adapter make sense. 

Anyways, IMO your PR is fine and we can always add this additional functionality in a later PR. I just wanna discuss it here, since we are already on the topic.

**Comment by oliverschulze** [comment]
ok, so this PR should be fine, good!
The issue with the on/off switch, I also have with hue-lights and also in combination with other adapters, like the homekit adapter. So I think, controlling that in the cloud adapter would be the wrong place, it would make more sense in the light adapters. I have seen a commit, that had been done explicitely, to set brightness to 100% when turning on the lights and set it to 0% when turning off.

**Comment by AlCalzone** [comment]
> So I think, controlling that in the cloud adapter would be the wrong place, it would make more sense in the light adapters.

The thing is that that the adapters cannot know if setting both values makes sense or not. For example:
- If I have a "routine" defined in Alexa that turns on my lights and sets the colorTemp to 100% => thats fine
- However, if I just say "Alexa, turn xyz on" and the cloud adapter turns the lights on and also sets the colorTemp to 100% => thats not what I wanted.

For other adapters both scenarios look exactly the same. They get two state updates from the cloud adapter and thats it.

I think it **should** be the cloud adapter's job to minimize side effects from an Alexa request by only setting those states that semantically match the request. But it's also the job of the other adapters to **correctly describe** their states, so the cloud adapter can do that job.

**Comment by oliverschulze** [comment]
ah now I can see, what you mean, you're right it is controlled in the onOff part, I will implement something to prevent this, when there is also a switch in the configuration!

**Comment by oliverschulze** [comment]
AlCazone, I have commited a new patch, that is just controlling the switch, when turning on/off command is sent (when there is a switch within the configuration), I think that should  work, as you wanted, could you please test? Thanks!

In my setup it also is setting the brightness, but this is not a problem of the cloud adapter it is within the hue-adapter, that turns the level to 100% when turning on the lights.

**Comment by AlCalzone** [comment]
Thanks! I'll probably test tomorrow as I just came home and need some sleep :D

**Comment by GermanBluefox** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
Damn I forgot. Gonna test right away!

**Comment by AlCalzone** [comment]
This is much better than with the old version. On/Off now only targets the switch state, setting a percentage only targets the dimmer state.

One detail we forgot though. When I configure my Tradfri device as follows:
unbenannt
I would expect the adapter to also set the brightness to 100% when turning on. **This setting is currently ignored.** 
So one more rule should be put in for TurnOnRequests IMO:
- If there are percentage devices with their _on level_ set to something else than "last value", also set those to their defined _on level_.

**Comment by AlCalzone** [comment]
Anything new to test?

**Comment by oliverschulze** [comment]
AlCalzone: I have changed it, you can test it again, please!

**Comment by AlCalzone** [comment]
Will probably do tomorrow evening. Thanks!

**Comment by AlCalzone** [comment]
Does not work. And I think the check should be more exhaustive => when controlling on/off, also control dimmers with their "on level" defined.
I'll create a small PR on your branch with how I imagine the test.

**Comment by AlCalzone** [comment]
I created the PR on @oliverschulze 's fork. Once that is merged, this PR can be merged aswell.

**Comment by WolfspiritM** [comment]
Hello,

I'm rather new to ioBroker, but I've already made Alexa Skills for other home automations.
I've taken a look at the V2 implementation and I thought it's very messy and buggy.
So I've sat down and tried to make it more stable (at least for me).

I've removed all the ids, idos, idbs, idss...stuff and introduced "channels". Alexa now knows the channels "hue.0.Go and all the states that are added to the smart group including their type. That way it's easy to figure out if there is a switch within that channel for example or a dimmer to switch that instead of other numeric values.

So before merging this pull request it would be great of you guys could give my "rewrite" a test instead:
https://gitlab.com/Wolfspirit/ioBroker.cloud
That also fixes this issue and many more for example:
- Table breaks if a new hue device is added in cloud admin
- Increment/DecrementPercentage didn't work right cause of a math error
- Unable to control multiple HUE devices in one virtual group as the color gets overridden
- ... 

Also it includes ApplianceTypes so you can tell Alexa that it's a Light or a Switch (so grouping works).
image


And it has working SetColorTemperature, IncrementColorTemperature and DecrementColorTemperature.

I'm not done yet but I've been sitting on it the whole night so I need a break. I need to still test Locks and Temperature to make sure they still work as well as RGB Devices (HUE works)...but I wanted to give you guys a heads up so you can let me know what you think so far...also right now there is a need to have "saturation" and "brightness" added to the smart group aswell if you want to use "hue" which I'm going to change, too.
Also the table header in admin is wrong at the moment.

**Comment by AlCalzone** [comment]
Gonna test asap!

**Comment by oliverschulze** [comment]
what does the travis-ci check, check? Why does it exactly fail? Can someone explain?
AlCazone, as I can see from you screenshots, you are speaking german language, I am also from germany, so you can try to explain me, what exactly you mean in german language, maybe  it's more easy.

**Comment by WolfspiritM** [comment]
It seems it "fails" cause the CI build job got canceled somehow. However it doesn't show why it got canceled (maybe some travis-ci hickups?)
https://travis-ci.org/ioBroker/ioBroker.cloud/builds/324279994

**Comment by AlCalzone** [comment]
> AlCazone, as I can see from you screenshots, you are speaking german language, I am also from germany, so you can try to explain me, what exactly you mean in german language, maybe it's more easy.

Gerne. Mein Ziel ist es, dass beim Anschalten nicht nur Switches, sondern auch Dimmer betätigt werden, bei denen das "On-Level" im Konfigurationsdialog festgelegt ist. Also im Falle von dem Screenshot hier https://github.com/ioBroker/ioBroker.cloud/pull/28#issuecomment-352695494
würde Brightness beim Anschalten auf 100% gesetzt, ColorTemperature aber nicht angefasst. Das ist in meinem PR auf deinem Branch implementiert und getestet.

Wenn du das mergst, wäre dieser PR imo fertig. Ich will jetzt aber erst mal @WolfspiritM's Änderungen testen, da der Code an sich etwas aufgeräumter wirkt als der Cloud-Adapter im aktuellen Zustand. Und er kann schon etwas mehr, d.h. mein anderer PR #35 wäre ebenfalls hinfällig.

**Comment by oliverschulze** [comment]
@AlCalzone: ah ok, dachte, das hätte ich genauso implementiert gehabt, so wie du es beschrieben hattest. Scheine wohl etwas vergessen zu haben. Dann übernehme ich mal deine Änderungen und du prüfst noch den PR von WolfspritiM's.

**Comment by oliverschulze** [comment]
ok, I have merged it with the master now and tested it, and it is still working

**Comment by AlCalzone** [comment]
After testing #40, I would prefer to merge that PR instead of this one. PR #35 is also unneccessary when merging #40.

**Comment by GermanBluefox** [comment]
I think this is not actual any more?

**Comment by AlCalzone** [comment]
No, this is superseded by the other PR #40 you just merged.

**Comment by modmax** [comment]
Think this issue can also be closed or the pull request denied.

**Comment by GermanBluefox** [comment]
Please reopen if still actual.

**Pull request closed without merging**
