### PR TITLE
Korrektur der Berechnung

### PR DESCRIPTION
**Pull request by Steiger04**
Abbildung von Kelvin -> % korrigiert

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you. I Hope it works, because I cannot test it :)

**Comment by Steiger04** [comment]
Hallo Bluefox,

bitte beide Merges wieder rückgängig machen. Das stimmt so nicht. So wie Du es umgesetzt hast funktioniert es aber auch nicht. Schaue mir gerade dei Details an. Warum nutzt die als normalisierte Einheit 'mared' und rechnest Kelvin nicht direkt linear in % um?

Grüße
Carsten

**Comment by WolfspiritM** [comment]
Hi, It would be great if you could keep the discussion in english.
Especially commit messages!
Also please use let instead of var for backend javascript! :-)

What exactly is the problem you're having?
I created a datapoint with unit "%" and without your changes when I ask alexa to set the color to "warm white" it sets that point to "100%".
If I ask Alexa to set the color to "cold" it sets that point to "0%".
If I ask Alexa to make the light warmer it increments the percent by "25%" as expected.
What adapter are you using or are you trying to control your own Datapoints?

Only thing that is wrong is anything that has "K" as unit cause the delta doesn't work as expected.
I have fixed that in my branch:
https://github.com/WolfspiritM/ioBroker.cloud/tree/more-fixes

It also reverts that changes here.

**Comment by GermanBluefox** [comment]
Hallo Carsten,
ich habe das vor einem Jahr implementiert und schon vergessen. :(

Gruß,
Bluefox

2018-01-21 12:57 GMT+01:00 carsten04 <notifications@github.com>:

**Comment by Apollon77** [comment]
@WolfspiritM "let" only when also strict is used ... else not node4 compatible!

**Comment by WolfspiritM** [comment]
@Apollon77 Yep. I'm fully aware of that. However the whole iobroker.cloud is not using strict and let instead of var. See here: https://github.com/ioBroker/ioBroker.cloud/commit/0fd3d99f860621e93486c9a889d7555dc50ef54f

**Comment by Apollon77** [comment]
But strict is there ... :-) https://github.com/ioBroker/ioBroker.cloud/commit/0fd3d99f860621e93486c9a889d7555dc50ef54f#diff-32444a554a6bcac1788c011ba4899a64R1

**Pull request merged**
