### PR TITLE
Fix TypeError when device is undefined

### LINKED ISSUE #86: Cloud adapter crashes when text2command does not respond
In this line
https://github.com/ioBroker/ioBroker.cloud/blob/6cb6f9a5c9660937e534e9fd6464990fbca32750/lib/alexaCustom.js#L43
`request.request.intent.slots.device` is `undefined` when called from
https://github.com/ioBroker/ioBroker.cloud/blob/6cb6f9a5c9660937e534e9fd6464990fbca32750/lib/alexaCustom.js#L159

Not sure how the adapter should respond in that case.

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes #86

### CODE REVIEW

**Comment by Apollon77** [comment]
question from my side is if not the whole stuff there should be removed ... if only used for custom skill then unneeded from now on. if also used by smarthome skill then fix is valid

**Comment by AlCalzone** [comment]
Not sure actually, @GermanBluefox ?
At least this is crashing my cloud adapter atm when no response from text2command is received.

**Comment by AlCalzone** [comment]
Works for me now without crashes:

cloud.0 | 2018-05-05 09:47:35.888 | debug | SessionEndedRequest: EXCEEDED_MAX_REPROMPTS
-- | -- | -- | --
cloud.0 | 2018-05-05 09:47:35.887 | debug | 1525506455885  ALEXA:  {"version":"1.0","session":{"new":false,"sessionId":"amzn1.echo-api.session.56177ca9-2a5e-49a9-909e-1879e9ce4d7a","application":{"applicationId":"amzn1.ask.skill.6cee68cd-3d15-4f4
cloud.0 | 2018-05-05 09:47:27.081 | debug | Response from text2command: Ich verstehe "der fernseher an" nicht
text2command.0 | 2018-05-05 09:47:27.073 | debug | sendTo "send" to system.adapter.cloud.0 from system.adapter.text2command.0
text2command.0 | 2018-05-05 09:47:27.073 | warn | Timeout for external processor: javascript.0.alexaCommand
text2command.0 | 2018-05-05 09:47:27.072 | info | processText: "askDevice der fernseher an"

**Comment by GermanBluefox** [comment]
Danke

**Pull request merged**
