### PR TITLE
Replace let with var for node 4

### PR DESCRIPTION
**Pull request by WolfspiritM**
Latest changes introduced "let" instead of "var" which breaks node 4.
This PR changes and fixes it.

### CODE REVIEW

**Comment by AlCalzone** [comment]
I kinda like the transition to using the block-scoped declarations (let/const) as this removes some potential sources of bugs. Could you try to undo your fix and instead put
```
'use strict';
```
at the top of the file?

**Comment by WolfspiritM** [comment]
As much as I'd like to use "let" as well I think moving to strict should be
done in a separate PR and to all files instead of just this one.

**Comment by AlCalzone** [comment]
sounds reasonable

**Comment by Apollon77** [comment]
Ok, tests lokk good, I merge it because it's only let->var replacements

**Pull request merged**
