### PR TITLE
Major bugfixes

### PR DESCRIPTION
**Pull request by AlCalzone**
This is an alternative proposal to #28, see https://github.com/ioBroker/ioBroker.cloud/pull/28#issuecomment-355525449 for a description. Opened a separate PR for clarity.

I think we should give this a try before merging any of the current PRs (#28 / #35).

### CODE REVIEW

**Comment by AlCalzone** [comment]
I didn't get very far testing this:
undefined
The two devices (Staubsauger and Test) consist of multiple states I manually grouped together with a small hack. By appending an extraneous `,` at the end of the smart name (so it was `"Test,"` and `"Staubsauger,"`), I could avoid the duplicate check of the config dialog.

**Comment by WolfspiritM** [comment]
This doesn't seem to use the changed admin html file.
Have you uploaded the controller "./iobroker upload cloud" so iobroker knows about the new files?

**Comment by AlCalzone** [comment]
> This doesn't seem to use the changed admin html file.

You're right. I thought I did but I'll try again.

**Comment by AlCalzone** [comment]
So when I try to control one of those hacked states, this happens:
```

cloud.0 | 2018-01-05 16:08:52.129 | error | at Decoder.Emitter.emit (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
-- | -- | -- | --
cloud.0 | 2018-01-05 16:08:52.129 | error | at Decoder. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Manager.ondecoded (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
cloud.0 | 2018-01-05 16:08:52.129 | error | at Socket. (/opt/iobroker/node_modules/iobroker.cloud/main.js:558:22)
cloud.0 | 2018-01-05 16:08:52.129 | error | at AlexaSH2.process (/opt/iobroker/node_modules/iobroker.cloud/lib/alexaSmartHomeV2.js:1101:33)
cloud.0 | 2018-01-05 16:08:52.129 | error | TypeError: Cannot read property 'split' of undefined
cloud.0 | 2018-01-05 16:08:52.128 | error | uncaught exception: Cannot read property 'split' of undefined
```

**Comment by WolfspiritM** [comment]
I think the problem is that alexa still has the old payloads.
Can you try removing the devices from alexa and ask alexa to pair them again?

I was thinking about removing the additionalApplianceDetails alltogether, cause it just causes trouble. Especially as a simple discovery doesn't update the device which means newly added states wouldn't register...

**Comment by WolfspiritM** [comment]
The new commit stops using additionalApplicationDetails over alexa but collects them from the smartDevices array we have available locally anyway...
That way new states added to a Smart Group will be recognized instantly

**Comment by AlCalzone** [comment]
I'll test again tomorrow with your new changes, enough for me today.

**Comment by Baenker** [comment]
this verson fixed #39 too. Looks realy great in my tests

**Comment by AlCalzone** [comment]
Works like a charm for me! Except setting the color temperature expects the state to be in mired (10^6/Kelvin) and is not rounded. I'll create a small PR on your branch with my changes that are already in #35, which should improve the handling of color temperatures.

**Comment by Baenker** [comment]
this version fixed #26 too.

**Comment by AlCalzone** [comment]
Works like a charm for me! Except setting the color temperature expects the state to be in mired (10^6/Kelvin) and is not rounded. 

I created a PR on your branch https://github.com/WolfspiritM/ioBroker.cloud/pull/1 that improves handling of color temperature states which are not defined in mireds (like the hue adapter) but in percent (tradfri) or raw kelvin (?).
When you merge that, I think this PR is ready.

**Comment by modmax** [comment]
Hi WolfspiritM, it works realy good.
Now I can also set the color without flickering or turning off the lamp.

But I've investigating:
If I choose a color and then dim the lamp i.e. to 60% and then change the color again,
then the dim level is at 100% again.
stehlampe

**Comment by WolfspiritM** [comment]
@modmax I don't have that problem... Lamp is red -> When I dim to 60% and make the lamp green afterwards it stays at 60% for me...with and without any on-level defined.
Can you try removing level from the group? That one isn't really needed but it shouldn't cause any problems having it in.

Only thing I noticed when trying that is that the "by ON" when you turn stuff on is sometimes ignored. I think when we try to control two things at once ("on" and "bri") it depends on. I think we should ignore the switch if a dimmer with a byON value is used.

**Comment by AlCalzone** [comment]
> I think when we try to control two things at once ("on" and "bri") it depends on which one triggers first.

In that case I think one of the states doesn't belong in the smartname. I'm not sure about hue, but tradfri can be controlled entirely with the brightness state.

> I think we should ignore the switch if a dimmer with a byON value is used.

That's something we discussed in #28. IMO we shouldn't because you can also group states from multiple devices in one smartname. For example I have multiple lights in my living room smart name. Some are dimmable, some are not.
If we absolutely have to do that for some reason, I think we should only apply that rule for states belonging to the same device. So if there are two devices grouped in one smartname:
* device A (switch + dimmer w/ on level)
* device B (switch)

dimmer A and switch B should be controlled.

**Comment by WolfspiritM** [comment]
I agree and as I'm working with channels I can separate the different devices :-)
So if the same channel (which should be the same device!) uses a level.dimmer and switch and bri has a byON value defined then we use that instead of the switch. That way both cases work.

**Comment by AlCalzone** [comment]
> I just wonder if there are devices that will only react to the switch when turned off. (Hue and Tradfri work fine with the dimmer)

I'm not sure. I just checked for ZWave and the dimmable ones don't even have an on/off state.

**Comment by WolfspiritM** [comment]
I now introduced a new "Default" byON value...and I now use that to define if we want to use the switch or the dimmer. The old "last value" byON state is now "default" so if you want the old behaviour you might want to switch back to "last value" (I didn't like the idea to make last value the default as that isn't always the last value if the light is changed manually).
If byON is set to default then we always use the switch for the device if one is present. This way it depends on the device to which value it will set the light when turned on (Tradfri returns to the original brightness while HUE goes full bright). If set to "last value" we use the dimmer if one is present and use the last value we know of ("valuesON").

@modmax I think I also figured out the problem you have. The reason why this is happening is that Alexa sends a brightness with the color which is always 100%. So the correct handling is setting it to 100%. If you really don't want that I now also added a way for you to ignore that by creating a property under the "Commons" Tab in the "bri" Object of the hue device. Call it "ignoreAlexaColor" and set it's value to "true" (just write it as text).

**Comment by GermanBluefox** [comment]
Looks very well. I hope you understand, that cloud is used by 4000 People? And if something will not work I will shift the whole blame on you :))

Joke :)

Thank you.

**Comment by GermanBluefox** [comment]
Please test. From github

**Comment by WolfspiritM** [comment]
Yes I understand that it's used by many people so I tried to test nearly all cases like Locks (with fake objects), Hue, Homematic, RGB Lights (with fake objects), Temperature read and set (with fake objects)...

I hope merging this doesn't mean it's "live". ;-)

I should have named this WIP for now :-)
There are still too much "log" messages in the code and it needs translation I think.
So just a few minor things. I will make a new pull request once I've that done :-)

**Comment by AlCalzone** [comment]
> So for your vacuum if you set everything to default and say "Alexa turn on..." it will start the vacuum but not change the power at all (which is correct). If you say "Set ... to 50 percent" then it will change the power. Only if you set "by ON" for the power to anything else then default it will fail as it will try to trigger that. Do you think that's a problem?

My original intention for the two states in one device was that I only have to say "turn on" and the vacuum gets turned on and its power set to the value I defined in the configuration.
Maybe in addition to the "don't set" config for dimmers you could add an option "set always" for switches? If that is set, then also trigger the switch, even when there's a configured dimmer.

**Comment by Apollon77** [comment]
SORRY GUYS!!!!

You broke node4 compatibility. See adapter tests!

https://travis-ci.org/ioBroker/ioBroker.cloud/jobs/325847055

```
/home/travis/build/ioBroker/ioBroker.cloud/tmp/node_modules/iobroker.cloud/lib/alexaSmartHomeV2.js:1014
            let friendlyUnit;
            ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/ioBroker/ioBroker.cloud/tmp/node_modules/iobroker.cloud/main.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

This can NOT be published!!

**Comment by Apollon77** [comment]
@GermanBluefox Please reopen till fixed :-) I can not do it

**Comment by WolfspiritM** [comment]
I created a new PR:
https://github.com/ioBroker/ioBroker.cloud/pull/42

**Comment by AlCalzone** [comment]
> You broke node4 compatibility. See adapter tests!
My bad O.O I thought that worked out of the box with Node 4. 
Is there anything that prohibits `"use strict;"` though?

**Comment by Apollon77** [comment]
Thank you for the fast reaction!

**Comment by Apollon77** [comment]
Can be retested from Github, node 4 fix merged

**Comment by modmax** [comment]
Hi again,
i've tested a little bit more and investigated following issues.
https://github.com/ioBroker/ioBroker.cloud/issues/43
https://github.com/ioBroker/ioBroker.cloud/issues/44

**Pull request merged**
